"""Typed contracts for Quant 2.0 inputs and outputs."""

from src.quant2.contracts.market_features import (
    FEATURE_SCHEMA_VERSION,
    AxisFeatureSnapshot,
    MarketFeatureSnapshot,
)
from src.quant2.contracts.market_overlays import OverlayInputs
from src.quant2.contracts.market_regime import (
    ConfidenceLevel,
    ContractValidationError,
    ForecastLabel,
    MarketAxis,
    MarketForecast,
    MarketReasonCode,
    MarketRegimeRecord,
    MarketScope,
    MarketStage,
    MarketStructure,
    ObservedMarketState,
    PrimaryTransitionLabel,
    ProbabilityStatus,
    RiskAppetite,
    ShortTermPriceShock,
    SourceAvailability,
    TransitionState,
    VolatilityState,
    canonical_sha256,
)
from src.quant2.contracts.market_technical_features import (
    MIN_RAW_OBSERVATIONS,
    TECHNICAL_FEATURE_SCHEMA_VERSION,
    TECHNICAL_INDICATOR_RULE_HASH,
    TECHNICAL_INDICATOR_RULE_VERSION,
    AdjustmentStatus,
    MarketCloseObservation,
    RevisionStatus,
    TechnicalFeatureStatus,
    TechnicalIndicatorSnapshot,
)
from src.quant2.contracts.trend_transition import (
    TREND_TRANSITION_SCHEMA_VERSION,
    TechnicalTransitionDirection,
    TrendTransitionSignal,
)

__all__ = [
    "FEATURE_SCHEMA_VERSION",
    "AxisFeatureSnapshot",
    "ConfidenceLevel",
    "ContractValidationError",
    "ForecastLabel",
    "MarketForecast",
    "MarketAxis",
    "MarketCloseObservation",
    "MarketFeatureSnapshot",
    "OverlayInputs",
    "MarketReasonCode",
    "MarketRegimeRecord",
    "MarketScope",
    "MarketStage",
    "MarketStructure",
    "MIN_RAW_OBSERVATIONS",
    "ObservedMarketState",
    "PrimaryTransitionLabel",
    "ProbabilityStatus",
    "RiskAppetite",
    "ShortTermPriceShock",
    "SourceAvailability",
    "TECHNICAL_FEATURE_SCHEMA_VERSION",
    "TECHNICAL_INDICATOR_RULE_HASH",
    "TECHNICAL_INDICATOR_RULE_VERSION",
    "TREND_TRANSITION_SCHEMA_VERSION",
    "TechnicalFeatureStatus",
    "TechnicalIndicatorSnapshot",
    "TechnicalTransitionDirection",
    "TrendTransitionSignal",
    "TransitionState",
    "VolatilityState",
    "AdjustmentStatus",
    "RevisionStatus",
    "canonical_sha256",
]
